author = "Franci Branda-Chen"

baseURL = 'https://fbc101.github.io/hugo-bootstrap-theme/'

copyright = "Franci Branda-Chen"
title = "CrimeGuard"

timeZone = 'America/New_York'

theme = "hugo-bootstrap-theme"
