# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Map application for a safe journey to wherever you need to be!"
images = ['images/logo.png','images/site-feature-image.png']
mainMenuLogo = "images/logo.png"

# For favicons
## Chrome Browser
themeColor = "#fff"
